language: node_js
node_js:
- '10'
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run lint
- npm test
after_success:
- npm run coverage
git:
  depth: 1
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  skip_cleanup: true
  email: ta7sudan@gmail.com
  api_key:
    secure: todo
  on:
    tags: true
    repo: ta7sudan/apiz-ng
    branch: master
